sudo: required

services:
  - docker

script:
  - echo "Deployment only!"

deploy:
  - provider: script
    script:
      - chmod +x docker/build.sh
      - docker/build.sh $TRAVIS_TAG
    on:
      branch: master
