sudo: required

services:
  - docker

branches:
  only:
  - master

addons:
  ssh_known_hosts: deplink.org

script:
  - chmod +x docker/build.sh
  - chmod +x phar/deploy.sh
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./docker/build.sh $TRAVIS_TAG; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./phar/deploy.sh $TRAVIS_TAG; fi
