sudo: required

services:
  - docker

script:
  - chmod +x docker/build.sh
  - chmod +x phar/deploy.sh
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./docker/build.sh $TRAVIS_TAG; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./phar/deploy.sh $TRAVIS_TAG; fi
